// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToCart = `INSERT INTO carts (id, user_id, product_id, quantity) VALUES ($1, $2, $3, $4) RETURNING id, user_id, product_id, quantity, created_at`

type AddToCartParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func scanCart(rawID, rawUserID, rawProductID pgtype.UUID, i *Cart) {
	i.ID = uuidFromPg(rawID)
	i.UserID = uuidFromPg(rawUserID)
	i.ProductID = uuidFromPg(rawProductID)
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, addToCart, uuidParam(arg.ID), uuidParam(arg.UserID), uuidParam(arg.ProductID), arg.Quantity)
	var i Cart
	var rawID, rawUserID, rawProductID pgtype.UUID
	err := row.Scan(&rawID, &rawUserID, &rawProductID, &i.Quantity, &i.CreatedAt)
	scanCart(rawID, rawUserID, rawProductID, &i)
	return i, err
}

const getCartItem = `SELECT id, user_id, product_id, quantity, created_at FROM carts WHERE id = $1`

func (q *Queries) GetCartItem(ctx context.Context, id uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartItem, uuidParam(id))
	var i Cart
	var rawID, rawUserID, rawProductID pgtype.UUID
	err := row.Scan(&rawID, &rawUserID, &rawProductID, &i.Quantity, &i.CreatedAt)
	scanCart(rawID, rawUserID, rawProductID, &i)
	return i, err
}

const listCartByUser = `SELECT id, user_id, product_id, quantity, created_at FROM carts WHERE user_id = $1 ORDER BY created_at DESC`

func (q *Queries) ListCartByUser(ctx context.Context, userID uuid.UUID) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCartByUser, uuidParam(userID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		var rawID, rawUserID, rawProductID pgtype.UUID
		if err := rows.Scan(&rawID, &rawUserID, &rawProductID, &i.Quantity, &i.CreatedAt); err != nil {
			return nil, err
		}
		scanCart(rawID, rawUserID, rawProductID, &i)
		items = append(items, i)
	}
	return items, rows.Err()
}

const removeFromCart = `DELETE FROM carts WHERE id = $1`

func (q *Queries) RemoveFromCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeFromCart, uuidParam(id))
	return err
}

const updateCartItem = `UPDATE carts SET quantity = $2 WHERE id = $1 RETURNING id, user_id, product_id, quantity, created_at`

type UpdateCartItemParams struct {
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartItem, uuidParam(arg.ID), arg.Quantity)
	var i Cart
	var rawID, rawUserID, rawProductID pgtype.UUID
	err := row.Scan(&rawID, &rawUserID, &rawProductID, &i.Quantity, &i.CreatedAt)
	scanCart(rawID, rawUserID, rawProductID, &i)
	return i, err
}
