// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `INSERT INTO products (id, name, description, price) VALUES ($1, $2, $3, $4) RETURNING id, name, description, price, created_at`

type CreateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Price       float64   `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, uuidParam(arg.ID), arg.Name, arg.Description, arg.Price)
	var i Product
	var rawID pgtype.UUID
	err := row.Scan(&rawID, &i.Name, &i.Description, &i.Price, &i.CreatedAt)
	i.ID = uuidFromPg(rawID)
	return i, err
}

const deleteProduct = `DELETE FROM products WHERE id = $1`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, uuidParam(id))
	return err
}

const getProduct = `SELECT id, name, description, price, created_at FROM products WHERE id = $1`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, uuidParam(id))
	var i Product
	var rawID pgtype.UUID
	err := row.Scan(&rawID, &i.Name, &i.Description, &i.Price, &i.CreatedAt)
	i.ID = uuidFromPg(rawID)
	return i, err
}

const listProducts = `SELECT id, name, description, price, created_at FROM products ORDER BY created_at DESC`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		var rawID pgtype.UUID
		if err := rows.Scan(&rawID, &i.Name, &i.Description, &i.Price, &i.CreatedAt); err != nil {
			return nil, err
		}
		i.ID = uuidFromPg(rawID)
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateProduct = `UPDATE products SET name = $2, description = $3, price = $4 WHERE id = $1 RETURNING id, name, description, price, created_at`

type UpdateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Price       float64   `json:"price"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct, uuidParam(arg.ID), arg.Name, arg.Description, arg.Price)
	var i Product
	var rawID pgtype.UUID
	err := row.Scan(&rawID, &i.Name, &i.Description, &i.Price, &i.CreatedAt)
	i.ID = uuidFromPg(rawID)
	return i, err
}
