// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

func uuidParam(id uuid.UUID) pgtype.UUID {
	return pgtype.UUID{Bytes: [16]byte(id), Valid: true}
}

func uuidFromPg(p pgtype.UUID) uuid.UUID {
	return uuid.UUID(p.Bytes)
}

const createUser = `INSERT INTO users (id, name, email) VALUES ($1, $2, $3) RETURNING id, name, email, created_at`

type CreateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, uuidParam(arg.ID), arg.Name, arg.Email)
	var i User
	var rawID pgtype.UUID
	err := row.Scan(&rawID, &i.Name, &i.Email, &i.CreatedAt)
	i.ID = uuidFromPg(rawID)
	return i, err
}

const deleteUser = `DELETE FROM users WHERE id = $1`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, uuidParam(id))
	return err
}

const getUser = `SELECT id, name, email, created_at FROM users WHERE id = $1`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, uuidParam(id))
	var i User
	var rawID pgtype.UUID
	err := row.Scan(&rawID, &i.Name, &i.Email, &i.CreatedAt)
	i.ID = uuidFromPg(rawID)
	return i, err
}

const listUsers = `SELECT id, name, email, created_at FROM users ORDER BY created_at DESC`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		var rawID pgtype.UUID
		if err := rows.Scan(&rawID, &i.Name, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		i.ID = uuidFromPg(rawID)
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateUser = `UPDATE users SET name = $2, email = $3 WHERE id = $1 RETURNING id, name, email, created_at`

type UpdateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, uuidParam(arg.ID), arg.Name, arg.Email)
	var i User
	var rawID pgtype.UUID
	err := row.Scan(&rawID, &i.Name, &i.Email, &i.CreatedAt)
	i.ID = uuidFromPg(rawID)
	return i, err
}
